### ISSUE TITLE
Installation error at calibre 4.21.0 64-bit

### ISSUE THREAD

**Issue by AndroLee** [jgoguen/calibre-kobo-driver#114]
I just update calibre to 4.21.0 and found somehow KoboTouchExtend is missing.
So I re-download it and however see an error message as below:

calibre, version 4.21.0
ERROR: Install plugin failed: A problem occurred while installing this plugin. This plugin will now be uninstalled. Please post the error message in details below into the forum thread for this plugin and restart calibre.

Traceback (most recent call last):
  File "site-packages\calibre\gui2\dialogs\plugin_updater.py", line 725, in _install_clicked
  File "site-packages\calibre\customize\ui.py", line 472, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 61, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 201, in load
  File "site-packages\polyglot\builtins.py", line 186, in reload
  File "site-packages\calibre\customize\zipplugin.py", line 185, in load_module
  File "calibre_plugins.kobotouch_extended.__init__", line 9, in <module>
ImportError: cannot import name KOBOTOUCHEXTENDED

**Comment by jgoguen** [comment]
This occasionally happens to plugins, but only on Windows and not only my plugins. Open Preferences, click Miscellaneous, then click the "Open calibre configuration directory". Once Explorer opens, close calibre. In the "plugins" directory, if a file named "KoboTouchExtended.zip" exists delete it. Then restart calibre and try again to install the plugin.

**Comment by jgoguen** [comment]
The problem is long-standing, but it's proven incredibly difficult to track down considering how infrequently it happens.

**Comment by AndroLee** [comment]
When I was trying to troubleshoot the issue as suggested, Calibre updated itself to 4.22 and I could install this plugin successfully again. So this could be an issue in 4.21 as @jgoguen said.
Thank you @jgoguen for maintaining this great plugin!
