### ISSUE TITLE
ERROR: Install plugin failed

### ISSUE THREAD

**Issue by McPwner** [jgoguen/calibre-kobo-driver#123]
I'm sorry if I misplaced report, but this is what I got:

calibre, version 5.1.0
Kobo Utilities - Switch device drivers: The KoboTouchExtended driver is not installed. There is nothing to switch between, so no changes have been made.

calibre, version 5.1.0
ERROR: Install plugin failed: A problem occurred while installing this plugin. This plugin will now be uninstalled. Please post the error message in details below into the forum thread for this plugin and restart calibre.

Traceback (most recent call last):
  File "site-packages\calibre\gui2\dialogs\plugin_updater.py", line 731, in _install_clicked
  File "site-packages\calibre\customize\ui.py", line 472, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 61, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 200, in load
  File "site-packages\polyglot\builtins.py", line 123, in reload
  File "importlib\__init__.py", line 169, in reload
  File "<frozen importlib._bootstrap>", line 602, in _exec
  File "site-packages\calibre\customize\zipplugin.py", line 184, in load_module
  File "calibre_plugins.kobotouch_extended.__init__", line 9, in <module>
ImportError: cannot import name 'KOBOTOUCHEXTENDED' from 'calibre_plugins.kobotouch_extended.device.driver' (<calibre Plugin Loader>)

**Comment by xtophe31** [comment]
I confirm, I have the same issue since I upgraded to Calibre 5.1

**Comment by jgoguen** [comment]
I can't reproduce this. Please file a new issue following the template given when you open a new issue.
