### ISSUE TITLE
Kobo Clara

### ISSUE THREAD

**Issue by urbainslh** [jgoguen/calibre-kobo-driver#124]
calibre, version 5.1.0
FOUT: Installatie plugin mislukt: Er is een probleem opgetreden tijdens het installeren van deze plug-in. Deze plug-in wordt nu verwijderd. Post het foutbericht in onderstaande details in de forumthread voor deze plug-in en start calibre opnieuw.

Traceback (most recent call last):
  File "site-packages\calibre\gui2\dialogs\plugin_updater.py", line 731, in _install_clicked
  File "site-packages\calibre\customize\ui.py", line 472, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 61, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 200, in load
  File "site-packages\polyglot\builtins.py", line 123, in reload
  File "importlib\__init__.py", line 169, in reload
  File "<frozen importlib._bootstrap>", line 602, in _exec
  File "site-packages\calibre\customize\zipplugin.py", line 184, in load_module
  File "calibre_plugins.kobotouch_extended.__init__", line 9, in <module>
ImportError: cannot import name 'KOBOTOUCHEXTENDED' from 'calibre_plugins.kobotouch_extended.device.driver' (<calibre Plugin Loader>)

**Comment by jgoguen** [comment]
I can't reproduce this. Please file a new issue following the template given when you open a new issue, including translating everything into English.
