### ISSUE TITLE
Installation error when Calibre language set to French - KePub Output 3.4.2 / Calibre 5.8.1

### ISSUE THREAD

**Issue by FlyThePlanet** [jgoguen/calibre-kobo-driver#132]
# Bug Checklist

These items are mandatory. If you need help finding this information submit the
bug report with as much completed as you can and ask for help finding the rest.

- [x] I am using the latest version of calibre to report this bug, which is: 5.8.1
- [x] I am using an official calibre release, not one from a third party (e.g.
    your Linux distro, Flatpak, Chocolatey package, Homebrew, etc.)
- [x] I am using the latest version of this plugin, which is: 3.4.2
- [x] My operating system is (e.g. Windows 10, Windows 8.1, Windows 8, macOS
    10.15.5, Fedora 32, Arch Linux, etc.): Windows 10 Pro 1909 64bits 
- [ ] I have included the full, complete, unmodified debug log from calibre
  - Directions for getting the debug log are under the "Logs" header below.
- [ ] I have translated the text in any screenshots and logs to English, or all
    screenshots and logs included are in English.

These items are optional. Fill in as much of them as possible. If something is
not applicable to your bug report, note that.

- [ ] I have installed the Scramble Epub plugin (see
    https://www.mobileread.com/forums/showthread.php?t=267998) and will attach
    a **scrambled** copy of the book I'm having problems with (attach a file by
    dragging and dropping onto the Github editor): no, not installed
  - [ ] If this is a conversion bug, I will also attach a **scrambled** copy of
    the converted book.
- [x] The path to my calibre library or to a book in my calibre library has
    non-ASCII characters: no
- [x] If I am using Windows 10, I (have/have not) enabled Windows' beta support
      for Unicode (see
      https://www.mobileread.com/forums/showpost.php?p=3988195&postcount=2052): I have done both
- [x] If I am using Windows 10, does this bug happens with beta Unicode support
    both enabled and disabled, only when enabled, or only when disabled? Both, whether disabled or enabled

# Describe the bug

Plugin installation not working when Calibre language is set to "French".

## Steps to Reproduce

Preferences -> Look & Feel -> Choose Language -> French
Preferences -> Plugins -> Get new plugins and install the 'KePub Output' plugin.

## Expected behavior

Plugin installed.

## Actual behaviour

Error message.

## Screenshots

If applicable, add screenshots to help explain your problem. If you are using
calibre in any language other than English, please either provide a translation
of any relevant text to English or switch calibre to use English first.

## Logs

```text
calibre, version 5.8.1
ERREUR : L’installation de l’extension a échoué: Un problème est survenu lors de l’installation de cette extension. Cette extension va être maintenant désinstallée. Veuillez svp bien vouloir poster le message d’erreur détaillé ci-dessous dans la discussion du forum relative à cette extension et redémarrer calibre.

Traceback (most recent call last):
  File "calibre\gui2\dialogs\plugin_updater.py", line 709, in _install_clicked
  File "calibre\customize\ui.py", line 472, in add_plugin
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 293, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.kepubout.__init__", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.kepubout.conversion.kepub_output", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.kepubout.container", line 49, in <module>
  File "calibre\customize\zipplugin.py", line 119, in load_translations
  File "gettext.py", line 261, in __init__
  File "gettext.py", line 456, in _parse
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 20: ordinal not in range(128)
```

## Additional context

The issue does not happen when the Calibre Language is set to English.

**Comment by jgoguen** [comment]
If you enable beta Unicode support in Windows (https://www.mobileread.com/forums/showpost.php?p=3988195&postcount=2052) does this still happen?

**Comment by FlyThePlanet** [comment]
Tried. Same issue...

`calibre, version 5.8.1
ERREUR : L’installation de l’extension a échoué: Un problème est survenu lors de l’installation de cette extension. Cette extension va être maintenant désinstallée. Veuillez svp bien vouloir poster le message d’erreur détaillé ci-dessous dans la discussion du forum relative à cette extension et redémarrer calibre.

Traceback (most recent call last):
  File "calibre\gui2\dialogs\plugin_updater.py", line 709, in _install_clicked
  File "calibre\customize\ui.py", line 472, in add_plugin
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 293, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.kepubout.__init__", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.kepubout.conversion.kepub_output", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.kepubout.container", line 49, in <module>
  File "calibre\customize\zipplugin.py", line 119, in load_translations
  File "gettext.py", line 261, in __init__
  File "gettext.py", line 456, in _parse
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 20: ordinal not in range(128)
`

**Comment by FlyThePlanet** [comment]
FYI, at first the path to the library was: "C:\Users\Username\Bibliothèque Calibre" with 1 non ASCII character.
So I uninstalled Calibre and ran a clean install setting up the library to "E:\Calibre eBooks", this time with no non ASCII character. But it doesn't change anything...
```
calibre, version 5.8.1
ERREUR : Exception non gérée: <b>UnicodeDecodeError</b>:'ascii' codec can't decode byte 0xc3 in position 20: ordinal not in range(128)

calibre 5.8.1  embedded-python: True is64bit: False
Windows-10-10.0.18362 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', '', 'Multiprocessor Free')
Interface language: fr
Successfully initialized third party plugins: DeDRM (7, 0, 0) && KePub Metadata Reader (3, 2, 9) && KePub Metadata Writer (3, 2, 12)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 316, in add_plugin
  File "calibre\customize\ui.py", line 472, in add_plugin
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 293, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.kepubout.__init__", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.kepubout.conversion.kepub_output", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.kepubout.container", line 49, in <module>
  File "calibre\customize\zipplugin.py", line 119, in load_translations
  File "gettext.py", line 261, in __init__
  File "gettext.py", line 456, in _parse
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 20: ordinal not in range(128)
```

**Comment by davidfor** [comment]
@jgoguen: I don't think the Unicode support setting matters. I updated my source, compiled the fr.po to an mo using Pedit v2.4.1 and put that in the output plugin. It then loaded successfully. And the same worked for the extended driver.

I didn't use the build process for this. I simply unzipped the installed version, changed the fr.mo, zipped it up again and moved it to the right place.

I did check the other languages, and there were no problems. Though, I'm not sure how to get the variants. Do those rely on an OS setting as well as the calibre settings?

**Comment by jgoguen** [comment]
I'm assuming this is Yet Another Windows Bug, but I found one thing which may help. I'm using calibre itself to build the MO files, but Kovid's msgfmt implementation says it doesn't handle plural forms, but I'm using plural forms. 

@FlyThePlanet can you download the plugins you're having trouble with from these links here and see if that ZIP file will install correctly?
[KePub Input.zip](https://github.com/jgoguen/calibre-kobo-driver/files/5761255/KePub.Input.zip)
[KePub Metadata Reader.zip](https://github.com/jgoguen/calibre-kobo-driver/files/5761256/KePub.Metadata.Reader.zip)
[KePub Metadata Writer.zip](https://github.com/jgoguen/calibre-kobo-driver/files/5761257/KePub.Metadata.Writer.zip)
[KePub Output.zip](https://github.com/jgoguen/calibre-kobo-driver/files/5761258/KePub.Output.zip)
[KoboTouchExtended.zip](https://github.com/jgoguen/calibre-kobo-driver/files/5761259/KoboTouchExtended.zip)

> I did check the other languages, and there were no problems. Though, I'm not sure how to get the variants. Do those rely on an OS setting as well as the calibre settings?

You can set `CALIBRE_OVERRIDE_LANG` to the language code you want to try out.

**Comment by FlyThePlanet** [comment]
> @FlyThePlanet can you download the plugins you're having trouble with from these links here and see if that ZIP file will install correctly?
> KePub Output.zip

Sorry for the late reply, but I can confirm it now works with this new version and Calibre in French.
Thanks!

**Comment by jgoguen** [comment]
I'm working on releasing v3.4.3 now, that will resolve the problem once it's pushed out.
