### ISSUE TITLE
KeyError: 'OEBPS/Text/Titlepage.xhtml'

### ISSUE THREAD

**Issue by faulander** [jgoguen/calibre-kobo-driver#137]
MacOS Big Sur
Calibre: 5.28
KoboToucExtended: 3.5.3

When uploading to by Kobo Aura H20 i get sometimes following error, always the same.
If i retry the book, it usually works after replugging the device. 
"Silently Ignore failed conversions" doesn't help in the settings.

```
'OEBPS/Text/Titlepage.xhtml'

Traceback (most recent call last):
  File "calibre/gui2/device.py", line 89, in run
  File "calibre/gui2/device.py", line 595, in _upload_books
  File "calibre_plugins.kobotouch_extended.device.driver", line 400, in upload_books
    return super(KOBOTOUCHEXTENDED, self).upload_books(
  File "calibre/devices/kobo/driver.py", line 2137, in upload_books
  File "calibre_plugins.kobotouch_extended.device.driver", line 211, in _modify_epub
    container = KEPubContainer(infile, common.log, self.clean_markup)
  File "calibre_plugins.kobotouch_extended.container", line 119, in __init__
    self.__run_async_over_content(self.forced_cleanup)
  File "calibre_plugins.kobotouch_extended.container", line 375, in __run_async_over_content
    self.__run_async(func, names)
  File "calibre_plugins.kobotouch_extended.container", line 368, in __run_async
    future.result(timeout=10)
  File "concurrent/futures/_base.py", line 432, in result
  File "concurrent/futures/_base.py", line 388, in __get_result
  File "concurrent/futures/thread.py", line 57, in run
  File "calibre_plugins.kobotouch_extended.container", line 310, in forced_cleanup
    self.flush_cache()
  File "calibre_plugins.kobotouch_extended.container", line 170, in flush_cache
    self.__run_async(self.__flush_cache_impl, args)
  File "calibre_plugins.kobotouch_extended.container", line 368, in __run_async
    future.result(timeout=10)
  File "concurrent/futures/_base.py", line 432, in result
  File "concurrent/futures/_base.py", line 388, in __get_result
  File "concurrent/futures/thread.py", line 57, in run
  File "calibre_plugins.kobotouch_extended.container", line 174, in __flush_cache_impl
    self.commit_item(name, keep_parsed=True)
  File "calibre/ebooks/oeb/polish/container.py", line 1025, in commit_item
  File "calibre/ebooks/oeb/polish/container.py", line 1011, in serialize_item
KeyError: 'OEBPS/Text/Titlepage.xhtml'

```

**Comment by jgoguen** [comment]
That's quite unusual, I wouldn't expect it to start working just because you unplugged and plugged back in. Can you install the ScrambleEbook plugin and attach the scrambled ePub to this issue? The actual error is coming out of calibre core code, but maybe I'm doing something while flushing the cache that's putting it into an unexpected state.

**Comment by faulander** [comment]
The problem is definately not the Ebook, because on the next try that exact Ebook works. It’s also only if i try to transfer a batch of ebooks to the Kobo - if i do it one by one the error is not happening. It works - sometimes up to 3-4, sometimes up to 5 - Ebooks then the error appears. I didn’t manage to tranfer more than 10 Ebooks without the error.
Maybe a problem with the async code?

**Comment by jgoguen** [comment]
A problem with the async code is certainly possible. I'm still not able to reproduce but I'll keep trying.

**Comment by jgoguen** [comment]
I haven't been able to reproduce this. Can you update calibre and the plugin, see if this is still happening, and if so include the calibre debug log and a scrambled version of the book? I know it's working on the book next time, but I need something to work with as I try to figure this out and I'm not having any problems even uploading a few dozen books at once.

**Comment by faulander** [comment]
My Kobo Aura H20 is bricked :/ My new Sage is on the way. If i can reproduce it there, i’ll get back to you!
