### ISSUE TITLE
Obok DeDRM plugin not functioning in Calibre 6.0

### ISSUE THREAD

**Issue by Icendra** [jgoguen/calibre-kobo-driver#146]
# Bug Checklist

These items are mandatory. If you need help finding this information submit the
bug report with as much completed as you can and ask for help finding the rest.

- [X ] I am using the latest version of calibre to report this bug, which is:
- [ X] I am using an official calibre release, not one from a third party (e.g.
    your Linux distro, Flatpak, Chocolatey package, Homebrew, etc.)
- [X ] I am using the latest version of this plugin, which is: 3.4.3
- [X ] My operating system is (e.g. Windows 10, Windows 8.1, Windows 8, macOS
    10.15.5, Fedora 32, Arch Linux, etc.): Windows 11 Home, Version 21H2
- [X ] I have included the full, complete, unmodified debug log from calibre
  - Directions for getting the debug log are under the "Logs" header below.
- [X ] I have translated the text in any screenshots and logs to English, or all
    screenshots and logs included are in English.

These items are optional. Fill in as much of them as possible. If something is
not applicable to your bug report, note that.

- [n/a ] I have installed the Scramble Epub plugin (see
    https://www.mobileread.com/forums/showthread.php?t=267998) and will attach
    a **scrambled** copy of the book I'm having problems with (attach a file by
    dragging and dropping onto the Github editor).
  - [n/a ] If this is a conversion bug, I will also attach a **scrambled** copy of
    the converted book.
- [n/a ] The path to my calibre library or to a book in my calibre library has
    non-ASCII characters: yes/no
- [ ] If I am using Windows 10, I (have/have not) enabled Windows' beta support
      for Unicode (see
      https://www.mobileread.com/forums/showpost.php?p=3988195&postcount=2052)
I'm using Windows 11, so I'm not sure if this is still necessary
- [ ] If I am using Windows 10, does this bug happens with beta Unicode support
    both enabled and disabled, only when enabled, or only when disabled? 
I'm using Windows 11, so I'm not sure if this is still necessary

# Describe the bug

Obok DeDRM plugin not functioning in Calibre 6.0

## Steps to Reproduce

click on the Obok DeDRM button
error screen pops up

## Expected behavior

The list of kepub files downloaded from Kobo Desktop edition 4.33.1755 to my hard drive opens to allow me to select which books to import

## Actual behaviour

calibre, version 6.0.0
ERROR: Unhandled exception: <b>AttributeError</b>:type object 'QTableWidgetItem' has no attribute 'UserType'

calibre 6.0  embedded-python: True
Windows-10-10.0.22000 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.10.1
Windows: ('10', '10.0.22000', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 49, 0) && Barnes & Noble (1, 2, 16) && Goodreads (1, 5, 3) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0) && KePub Input (3, 4, 3) && KePub Metadata Reader (3, 4, 3) && KePub Metadata Writer (3, 4, 3) && KePub Output (3, 6, 0) && Obok DeDRM (7, 1, 0)
Traceback (most recent call last):
  File "calibre_plugins.obok_dedrm.action", line 135, in launchObok
  File "calibre_plugins.obok_dedrm.dialogs", line 102, in __init__
  File "calibre_plugins.obok_dedrm.dialogs", line 154, in populate_table
  File "calibre_plugins.obok_dedrm.dialogs", line 179, in populate_table_row
  File "calibre_plugins.obok_dedrm.dialogs", line 439, in __init__
  File "calibre_plugins.obok_dedrm.dialogs", line 412, in __init__
AttributeError: type object 'QTableWidgetItem' has no attribute 'UserType'

## Screenshots

If applicable, add screenshots to help explain your problem. If you are using
calibre in any language other than English, please either provide a translation
of any relevant text to English or switch calibre to use English first.

## Logs

Restart calibre in debug mode. Paste the full calibre debug log here. To get the
debug log:

1. Find the `Preferences` button in the calibre toolbar.
1. Click the arrow to the right of `Preferences`.
1. Select the `Restart in debug mode` menu item.
   1. This will shut down and restart calibre immediately. Calibre will
      automatically restart, but it may take a few seconds.
   1. You will see a notification informing you that you have started calibre
      in debug mode. Click `OK`.
1. Do the minimum possible steps to reproduce the bug.
1. Close calibre.
   1. This will automatically display the debug log. Copy and paste the entire
      log in the blank space here (between `` ```text `` and `` ``` ``)

```text
calibre Debug log
calibre 6.0  embedded-python: True
Windows-10-10.0.22000 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.10.1
Windows: ('10', '10.0.22000', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 49, 0) && Barnes & Noble (1, 2, 16) && Goodreads (1, 5, 3) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0) && KePub Input (3, 4, 3) && KePub Metadata Reader (3, 4, 3) && KePub Metadata Writer (3, 4, 3) && KePub Output (3, 6, 0) && Obok DeDRM (7, 1, 0)
calibre 6.0  embedded-python: True
Windows-10-10.0.22000 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.10.1
Windows: ('10', '10.0.22000', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 49, 0) && Barnes & Noble (1, 2, 16) && Goodreads (1, 5, 3) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0) && KePub Input (3, 4, 3) && KePub Metadata Reader (3, 4, 3) && KePub Metadata Writer (3, 4, 3) && KePub Output (3, 6, 0) && Obok DeDRM (7, 1, 0)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 93.6046065259117 x 93.62457337883959
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.22] splash screen shown
[0.22] Initializing db...
[8.31] db initialized
[8.31] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[13.80] main UI initialized...
[13.80] Hiding splash screen
calibre 6.0  embedded-python: True
Windows-10-10.0.22000 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.10.1
Windows: ('10', '10.0.22000', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 49, 0) && Barnes & Noble (1, 2, 16) && Goodreads (1, 5, 3) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0) && KePub Input (3, 4, 3) && KePub Metadata Reader (3, 4, 3) && KePub Metadata Writer (3, 4, 3) && KePub Output (3, 6, 0) && Obok DeDRM (7, 1, 0)
Traceback (most recent call last):
  File "calibre_plugins.obok_dedrm.action", line 135, in launchObok
  File "calibre_plugins.obok_dedrm.dialogs", line 102, in __init__
  File "calibre_plugins.obok_dedrm.dialogs", line 154, in populate_table
  File "calibre_plugins.obok_dedrm.dialogs", line 179, in populate_table_row
  File "calibre_plugins.obok_dedrm.dialogs", line 439, in __init__
  File "calibre_plugins.obok_dedrm.dialogs", line 412, in __init__
AttributeError: type object 'QTableWidgetItem' has no attribute 'UserType'

Starting QuickView
[17.33] splash screen hidden
[17.33] Started up in 17.33 seconds with 125680 books
Running Obok DeDRM v7.1.0
DEBUG:   10.8 didn't find device
Obok v4.0.0
Copyright © 2012-2020 Physisticated et al.
C:\Users\klewe\AppData\Local\Temp\tmpnylau1e9
DEBUG:   11.5 got kobodir C:\Users\klewe\AppData\Local\Kobo\Kobo Desktop Edition
Found 28 possible keys to try.

```

## Additional context

Please let me know if you need further information about my operating system for full diagnostics

**Comment by Icendra** [comment]
Please disregard. My issue was with the DeDRM tools and not the input plugin. I have been directed to updated tools that have fixed my issue.
