### ISSUE TITLE
Issues with a file containing brackets inside the .epub file

### ISSUE THREAD

**Issue by gabfv** [jgoguen/calibre-kobo-driver#169]
# Bug Checklist

These items are mandatory. If you need help finding this information submit the
bug report with as much completed as you can and ask for help finding the rest.

- [x] I am using the latest version of calibre to report this bug, which is:
7.15.0
- [x] I am using an official calibre release, not one from a third party (e.g.
    your Linux distro, Flatpak, Chocolatey package, Homebrew, etc.)
- [x] I am using the latest version of this plugin, which is:
3.6.7
- [x] My operating system is (e.g. Windows 10, Windows 8.1, Windows 8, macOS
    10.15.5, Fedora 32, Arch Linux, etc.):
Windows 11
- [x] I have included the full, complete, unmodified debug log from calibre
  - Directions for getting the debug log are under the "Logs" header below.
- [x] I have translated the text in any screenshots and logs to English, or all
    screenshots and logs included are in English.

These items are optional. Fill in as much of them as possible. If something is
not applicable to your bug report, note that.

- [ ] I have installed the Scramble Epub plugin (see
    https://www.mobileread.com/forums/showthread.php?t=267998) and will attach
    a **scrambled** copy of the book I'm having problems with (attach a file by
    dragging and dropping onto the Github editor).
  - [ ] If this is a conversion bug, I will also attach a **scrambled** copy of
    the converted book.
- [x] The path to my calibre library or to a book in my calibre library has
    non-ASCII characters: yes/no
No (well, not outside the .epub)
- [ ] If I am using Windows 10, I (have/have not) enabled Windows' beta support
      for Unicode (see
      https://www.mobileread.com/forums/showpost.php?p=3988195&postcount=2052)
- [ ] If I am using Windows 10, does this bug happens with beta Unicode support
    both enabled and disabled, only when enabled, or only when disabled?

# Describe the bug

In short, I can't send an .epub to my Kobo Libra because of an issue described below.

The error message in particular:
```text
[Errno 2] No such file or directory: 'C:\\Users\\user2\\AppData\\Local\\Temp\\calibre_06mpjvie\\8p22bpju_epub_container\\OEBPS\\GWGC_%28eBook%29.xhtml'.
```

I noticed the parent folders of that file in the error message exists, however the filename isn't correct.
If I use 7-zip to extract the epub, I see this file, which has "(eBook)" in its filename:
```text
"C:\Users\user2\Calibre Library\Stephen R. Covey\Great Work Great Career (40)\Great Work Great Career - Stephen R. Covey\OEBPS\GWGC_(eBook).xhtml"
```

But then, the content.opf file has this particular line in it:
```xml
<item id="GWGC_-eBook-" href="GWGC_%28eBook%29.xhtml" media-type="application/xhtml+xml" />
```

So, if I rename the file inside the .epub from:
``` OEBPS\GWGC_(eBook).xhtml ```
to:
``` OEBPS\GWGC_eBook.xhtml ```

And then change this line in the OEBPS\content.opf file from:
``` <item id="GWGC_-eBook-" href="GWGC_%28eBook%29.xhtml" media-type="application/xhtml+xml" /> ```
to:
``` <item id="GWGC_-eBook-" href="GWGC_eBook.xhtml" media-type="application/xhtml+xml" /> ```

I now can send the book to my Kobo, because there is no more issue with the filepath.
So I think the issue lies with the way the path is parsed from the content.opf file inside the .epub. 

Also, I'm not sure if this is the plugin's fault, or Calibre itself, so I'd like some advice on whether the issue is opened at the right place.

## Steps to Reproduce

Steps to reproduce the behavior (as detailed as you can):

Right-click on the book to "Send to device" while the Kobo is plugged in, then after a short while, the error message appears.

## Expected behavior

Ideally, I think it should be able to convert the %28 and %29 to brackets for the file path by itself, but if not, maybe a clearer error message that the content.opf has non-convertible character(s) in file(s) it reference?

## Actual behaviour

The following error happens when trying to send the book to my Kobo:
```text
[Errno 2] No such file or directory: 'C:\\Users\\user2\\AppData\\Local\\Temp\\calibre_06mpjvie\\8p22bpju_epub_container\\OEBPS\\GWGC_%28eBook%29.xhtml'.
```

## Screenshots

If applicable, add screenshots to help explain your problem. If you are using
calibre in any language other than English, please either provide a translation
of any relevant text to English or switch calibre to use English first.

## Logs

Restart calibre in debug mode. Paste the full calibre debug log here. To get the
debug log:

1. Find the `Preferences` button in the calibre toolbar.
1. Click the arrow to the right of `Preferences`.
1. Select the `Restart in debug mode` menu item.
   1. This will shut down and restart calibre immediately. Calibre will
      automatically restart, but it may take a few seconds.
   1. You will see a notification informing you that you have started calibre
      in debug mode. Click `OK`.
1. Do the minimum possible steps to reproduce the bug.
1. Close calibre.
   1. This will automatically display the debug log. Copy and paste the entire
      log in the blank space here (between `` ```text `` and `` ``` ``)

```text
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 7.15  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: KePub Metadata Reader (3, 4, 3) && KePub Metadata Writer (3, 4, 3) && KoboTouchExtended (3, 6, 7)
calibre 7.15  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: KePub Metadata Reader (3, 4, 3) && KePub Metadata Writer (3, 4, 3) && KoboTouchExtended (3, 6, 7)
QPA platform: windows
devicePixelRatio: 1.5
logicalDpi: 96.0 x 96.0
physicalDpi: 110.21016949152542 x 109.83783783783784
[0.00] Starting up...
[0.00] Showing splash screen...
[0.14] splash screen shown
[0.14] Initializing db...
[0.14] db initialized
[0.14] Constructing main UI...
[0.44] GUI main window shown
[0.52] main UI initialized...
[0.52] Hiding splash screen
Storage number map:
{(7, 0): [(4, 'C')],
 (7, 1): [(2, 'F')],
 (7, 2): [(2, 'E')],
 (7, 3): [(1, 'K')],
 (7, 4): [(2, 'D')],
 (7, 5): [(1, 'G')]}
Storage number for USBSTOR\DISK&VEN_LINUX&PROD_FILE-STOR_GADGET&REV_0409\N428450119607&0: StorageDeviceNumber(type=7, number=5, partition_number=0)
Drive letters for USBDevice(vendor_id=0x2237 product_id=0x4237 bcd=0x409 devid=usb\vid_2237&pid_4237&rev_0409 devinst=28)
{'drive_letters': ['G'],
 'pnp_id_map': {'G': '\\\\?\\usbstor#disk&ven_linux&prod_file-stor_gadget&rev_0409#n428450119607&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 'readonly_drives': set(),
 'sort_map': {'G': (5, 1)}}
Job: 0 Get device information started
DEBUG:    0.0 device_version_info - start
DEBUG:    0.0 device_version_info - version_file=G:\.kobo\version
DEBUG:    0.0 device_version_info - have opened version_file
DEBUG:    0.0 device_version_info - self._device_version_info= ['N428450119607', '4.9.77', '4.39.23027', '4.9.77', '4.9.77', '00000000-0000-0000-0000-000000000390']
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.1 KoboTouch:books - oncard='None'
2024-07-30 17:20:03 [DEBUG] KoboTouchExtended:settings: settings=                                                                  2024-07-30 17:20:03 [DEBUG] <calibre.utils.config_base.OptionValues object at 0x00000229770A7610>
DEBUG:    0.1 KoboTouch:books - oncard='None', prefix='G:\'
DEBUG:    0.1 device_version_info - start
DEBUG:    0.1 Kobo device: Kobo Libra Colour
DEBUG:    0.1 Version of driver: (3, 6, 7) Has kepubs: True
DEBUG:    0.1 Version of firmware: (4, 39, 23027) Has kepubs: True
DEBUG:    0.1 Firmware supports cover image tree: True
2024-07-30 17:20:03 [DEBUG] KoboTouchExtended:settings: settings=                                                                  2024-07-30 17:20:03 [DEBUG] <calibre.utils.config_base.OptionValues object at 0x00000229770A6850>
DEBUG:    0.1 KoboTouch:books - opts.extra_customization= []
DEBUG:    0.1 KoboTouch:books - driver options= Driver:KoboTouchExtended, Options - format_map: ['kepub', 'epub', 'cbr', 'cbz', 'pdf', 'txt'], use_subdirs: True, read_metadata: True, use_author_sort: False, save_template: {author_sort}/{title} - {authors}, extra_customization: [], manage_collections: True, use_collections_columns: True, collections_columns: , use_collections_template: False, collections_template: , create_collections: False, delete_empty_collections: False, ignore_collections_names: , upload_covers: False, dithered_covers: False, keep_cover_aspect: False, upload_grayscale: False, letterbox_fs_covers: False, letterbox_fs_covers_color: #000000, png_covers: False, show_archived_books: False, show_previews: False, show_recommendations: False, update_series: True, force_series_id: False, update_core_metadata: False, update_purchased_kepubs: False, update_device_metadata: True, update_subtitle: False, subtitle_template: , update_bookstats: False, bookstats_wordcount_template: , bookstats_pagecount_template: , bookstats_timetoread_upper_template: , bookstats_timetoread_lower_template: , modify_css: False, override_kobo_replace_existing: True, support_newer_firmware: False, debugging_title: , driver_version: 3.6.7, extra_features: True, use_template: False, kepubify_template: , upload_encumbered: False, skip_failed: True, hyphenate: False, smarten_punctuation: False, clean_markup: False, full_page_numbers: False, disable_hyphenation: False, file_copy_dir: , hyphenate_chars: 6, hyphenate_chars_before: 3, hyphenate_chars_after: 3, hyphenate_limit_lines: 2
DEBUG:    0.1 KoboTouch:books - prefs['manage_device_metadata']= on_connect
DEBUG:    0.1 KoboTouch:books - set_debugging_title to ''
DEBUG:    0.1 KoboTouch:books - length bl=0
DEBUG:    0.1 KoboTouch:books - length bl after sync=0
DEBUG:    0.1 KoboTouch:books - reading device database
DEBUG:    0.1 Database Version:  175
DEBUG:    0.1 KoboTouch:books - shelf list: []
DEBUG:    0.1 KoboTouch:books - query= SELECT Title, Attribution, DateCreated, ContentID, MimeType, ContentType, ImageId, ReadStatus, Description, Publisher , ___ExpirationStatus, FavouritesIndex, Accessibility, Language, IsDownloaded, ISBN, Series, SeriesNumber, ___UserID, ExternalId, Subtitle, SeriesID, SeriesNumberFloat, StorePages, StoreWordCount, StoreTimeToReadLowerEstimate, StoreTimeToReadUpperEstimate FROM content  WHERE BookID IS NULL  AND ((Accessibility = -1 AND IsDownloaded in ('true', 1 ))       OR (Accessibility IN (1,2,8,9) and IsDownloaded in ('true', 1))         )  AND (externalId IS NULL OR externalId = '') AND contentId NOT LIKE 'file:///mnt/sd/%'
DEBUG:    0.1 KoboTouch:books - automatically managing metadata
DEBUG:    0.1 KoboTouch:books - self.kobo_series_dict= {}
DEBUG:    0.1 KoboTouch:books - about to sync_booklists
DEBUG:    0.1 USBMS: starting sync_booklists
DEBUG:    0.1 USBMS: finished sync_booklists
DEBUG:    0.1 KoboTouch:books - have done sync_booklists
DEBUG:    0.1 KoboTouch:books - end - oncard='None'
DEBUG:    0.1 KoboTouch:books - oncard='carda'
DEBUG:    0.1 KoboTouch:books - Asked to process 'carda', but do not have one!
DEBUG:    0.1 KoboTouch:books - oncard='cardb'
DEBUG:    0.1 KoboTouch:books - Asked to process 'cardb', but do not have one!
DeviceJob: 2 Get list of books on device done, calling callback
DEBUG:    0.1 DeviceJob: metadata_downloaded: Starting set_books_in_library
DEBUG:    0.1 DeviceJob: set_books_in_library: books to process= 0
DEBUG:    0.1 DeviceJob: set_books_in_library finished: time= 0.001003265380859375
DEBUG:    0.1 DeviceJob: metadata_downloaded: updating views
DEBUG:    0.1 DeviceJob: metadata_downloaded: syncing
2024-07-30 17:20:03 [DEBUG] KoboTouchExtended:settings: settings=                                                                  2024-07-30 17:20:03 [DEBUG] <calibre.utils.config_base.OptionValues object at 0x0000022977069950>
2024-07-30 17:20:03 [DEBUG] KoboTouchExtended:settings: settings=                                                                  2024-07-30 17:20:03 [DEBUG] <calibre.utils.config_base.OptionValues object at 0x0000022977070B10>
DEBUG:    0.1 DeviceJob: metadata_downloaded: refreshing ondevice
DEBUG:    0.1 DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 3 Send metadata to device started
DEBUG:    0.1 KOBO:sync_booklists - start
DEBUG:    0.1 KoboTouch:update_device_database_collections - oncard='main'
DEBUG:    0.1 KoboTouch:update_device_database_collections - device='Driver:KoboTouchExtended, Options - format_map: ['kepub', 'epub', 'cbr', 'cbz', 'pdf', 'txt'], use_subdirs: True, read_metadata: True, use_author_sort: False, save_template: {author_sort}/{title} - {authors}, extra_customization: [], manage_collections: True, use_collections_columns: True, collections_columns: , use_collections_template: False, collections_template: , create_collections: False, delete_empty_collections: False, ignore_collections_names: , upload_covers: False, dithered_covers: False, keep_cover_aspect: False, upload_grayscale: False, letterbox_fs_covers: False, letterbox_fs_covers_color: #000000, png_covers: False, show_archived_books: False, show_previews: False, show_recommendations: False, update_series: True, force_series_id: False, update_core_metadata: False, update_purchased_kepubs: False, update_device_metadata: True, update_subtitle: False, subtitle_template: , update_bookstats: False, bookstats_wordcount_template: , bookstats_pagecount_template: , bookstats_timetoread_upper_template: , bookstats_timetoread_lower_template: , modify_css: False, override_kobo_replace_existing: True, support_newer_firmware: False, debugging_title: , driver_version: 3.6.7, extra_features: True, use_template: False, kepubify_template: , upload_encumbered: False, skip_failed: True, hyphenate: False, smarten_punctuation: False, clean_markup: False, full_page_numbers: False, disable_hyphenation: False, file_copy_dir: , hyphenate_chars: 6, hyphenate_chars_before: 3, hyphenate_chars_after: 3, hyphenate_limit_lines: 2'
DEBUG:    0.1 KoboTouch::is_supported_fwversion - self.fwversion[:2] (4, 39)
DEBUG:    0.1 KoboTouch:update_device_database_collections - set_debugging_title to ''
DEBUG:    0.1 KoboTouch:update_device_database_collections - managing bookshelves and series.
DEBUG:    0.1 KoboTouch:update_device_database_collections - Number of series set=0 Number of books=0
DEBUG:    0.1 KoboTouch:update_device_database_collections - Number of core metadata set=0 Number of books=0
DEBUG:    0.1 KoboTouch:update_device_database_collections - Finished 
DEBUG:    0.1 USBMS: starting sync_booklists
DEBUG:    0.2 USBMS: finished sync_booklists
DEBUG:    0.2 KOBO:sync_booklists - end
DeviceJob: 3 Send metadata to device done, calling callback
DeviceJob: 3 Send metadata to device callback returned
Job: 0 Get device information finished
No details available.
Job: 1 Set library information finished
No details available.
Job: 2 Get list of books on device finished
No details available.
Job: 3 Send metadata to device finished
No details available.
[12.41] splash screen hidden
[12.41] Started up in 12.41 seconds with 61 books
2024-07-30 17:20:16 [DEBUG] KoboTouchExtended:settings: settings=                                                                  2024-07-30 17:20:16 [DEBUG] <calibre.utils.config_base.OptionValues object at 0x0000022977068F50>
Job: 4 Upload one book to the device: Great Work Great Career started
Device using plugboard epub KOBOTOUCHEXTENDED None
Setting metadata in: Great Work Great Career at: C:\Users\user2\AppData\Local\Temp\calibre_06mpjvie\lu8nllpqcaltmpfmt.epub
DEBUG:   14.6 KoboTouch:upload_books - 1 books
DEBUG:   14.6 KoboTouch:upload_books - files= ['C:\\Users\\user2\\AppData\\Local\\Temp\\calibre_06mpjvie\\lu8nllpqcaltmpfmt.epub']
DEBUG:   14.6 KoboTouch:upload_books: Processing book: Great Work Great Career by Stephen R. Covey
DEBUG:   14.6 KoboTouch:upload_books: file=C:\Users\user2\AppData\Local\Temp\calibre_06mpjvie\lu8nllpqcaltmpfmt.epub, name=Great Work Great Career - Stephen R. Covey_40.epub
2024-07-30 17:20:18 [WARN] kepubify_book - self.kepubify_template=''
2024-07-30 17:20:18 [WARN] kepubify_book - returning kepubify_book='True'
2024-07-30 17:20:18 [INFO] KoboTouchExtended:_modify_epub:Adding basic Kobo features to Great Work Great Career by Stephen R. Covey
2024-07-30 17:20:18 [DEBUG] KoboTouchExtended:settings: settings=                                                                  2024-07-30 17:20:18 [DEBUG] <calibre.utils.config_base.OptionValues object at 0x00000229770F1BD0>
2024-07-30 17:20:18 [INFO] KoboTouchExtended:_modify_epub:Failed conversions will be skipped
2024-07-30 17:20:18 [DEBUG] Creating KePub Container for ePub at C:\Users\user2\AppData\Local\Temp\calibre_06mpjvie\lu8nllpqcaltmpfmt.epub
2024-07-30 17:20:18 [DEBUG] Starting thread: func=forced_cleanup, name=OEBPS/CoverImage.xhtml
2024-07-30 17:20:18 [DEBUG] Forcing cleanup for file OEBPS/CoverImage.xhtml
2024-07-30 17:20:18 [DEBUG] Starting thread: func=forced_cleanup, name=OEBPS/GWGC_%28eBook%29.xhtml
2024-07-30 17:20:18 [DEBUG] Forcing cleanup for file OEBPS/GWGC_%28eBook%29.xhtml
2024-07-30 17:20:18 [DEBUG] Starting thread: func=forced_cleanup, name=OEBPS/toc.xhtml
2024-07-30 17:20:18 [DEBUG] Forcing cleanup for file OEBPS/toc.xhtml
2024-07-30 17:20:18 [DEBUG] thread processing None finished
2024-07-30 17:20:18 [ERROR] Unhandled exception in thread processing. [Errno 2] No such file or directory: 'C:\\Users\\user2\\AppData\\Local\\Temp\\calibre_06mpjvie\\8p22bpju_epub_container\\OEBPS\\GWGC_%28eBook%29.xhtml'
[Errno 2] No such file or directory: 'C:\\Users\\user2\\AppData\\Local\\Temp\\calibre_06mpjvie\\8p22bpju_epub_container\\OEBPS\\GWGC_%28eBook%29.xhtml'

Traceback (most recent call last):
  File "calibre\gui2\device.py", line 112, in run
  File "calibre\gui2\device.py", line 646, in _upload_books
  File "calibre_plugins.kobotouch_extended.device.driver", line 422, in upload_books
  File "calibre\devices\kobo\driver.py", line 2239, in upload_books
  File "calibre_plugins.kobotouch_extended.device.driver", line 204, in _modify_epub
  File "calibre_plugins.kobotouch_extended.container", line 122, in __init__
  File "calibre_plugins.kobotouch_extended.container", line 392, in __run_async_over_content
  File "calibre_plugins.kobotouch_extended.container", line 379, in __run_async
  File "calibre_plugins.kobotouch_extended.container", line 375, in __run_async
  File "concurrent\futures\_base.py", line 449, in result
  File "concurrent\futures\_base.py", line 401, in __get_result
  File "concurrent\futures\thread.py", line 58, in run
  File "calibre_plugins.kobotouch_extended.container", line 286, in forced_cleanup
  File "calibre\ebooks\oeb\polish\container.py", line 611, in raw_data
  File "calibre\ebooks\oeb\polish\container.py", line 1068, in open
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\user2\\AppData\\Local\\Temp\\calibre_06mpjvie\\8p22bpju_epub_container\\OEBPS\\GWGC_%28eBook%29.xhtml'
```

## Additional context

Add any other information you think might be helpful.

**Comment by jgoguen** [comment]
Thanks for the report! A fixed version should be out soon. I need to build new packages and upload them to MobileRead, calibre usually makes the updates available within an hour or so. Or you can grab the files from the release page in this repo once release v3.6.8 shows up and install it manually if you don't want to wait.
