### ISSUE TITLE
Typerror processing comment inside body tag (nav.xhtml)

### ISSUE THREAD

**Issue by 0x6f677548** [jgoguen/calibre-kobo-driver#172]
I have a book that cannot be sent to the device and raises this error:

```
calibre, version 7.16.0
ERROR: Error: Error communicating with device

Failed to process BookName: expected string or bytes-like object, got '_cython_3_0_10.cython_function_or_method'

Traceback (most recent call last):
  File "calibre_plugins.kobotouch_extended.device.driver", line 187, in _modify_epub
  File "calibre_plugins.kobotouch_extended.common", line 238, in modify_epub
  File "calibre_plugins.kobotouch_extended.container", line 398, in convert
  File "calibre_plugins.kobotouch_extended.container", line 394, in __run_async_over_content
  File "calibre_plugins.kobotouch_extended.container", line 381, in __run_async
  File "calibre_plugins.kobotouch_extended.container", line 377, in __run_async
  File "concurrent\futures\_base.py", line 449, in result
  File "concurrent\futures\_base.py", line 401, in __get_result
  File "concurrent\futures\thread.py", line 58, in run
  File "calibre_plugins.kobotouch_extended.container", line 523, in add_kobo_spans
  File "calibre_plugins.kobotouch_extended.container", line 589, in _add_kobo_spans_to_node
  File "calibre_plugins.kobotouch_extended.container", line 539, in _add_kobo_spans_to_node
  File "re\__init__.py", line 176, in search
TypeError: expected string or bytes-like object, got '_cython_3_0_10.cython_function_or_method'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\gui2\device.py", line 112, in run
  File "calibre\gui2\device.py", line 646, in _upload_books
  File "calibre_plugins.kobotouch_extended.device.driver", line 342, in upload_books
  File "calibre\devices\kobo\driver.py", line 2270, in upload_books
  File "calibre_plugins.kobotouch_extended.device.driver", line 211, in _modify_epub
  File "calibre_plugins.kobotouch_extended.device.driver", line 187, in _modify_epub
  File "calibre_plugins.kobotouch_extended.common", line 238, in modify_epub
  File "calibre_plugins.kobotouch_extended.container", line 398, in convert
  File "calibre_plugins.kobotouch_extended.container", line 394, in __run_async_over_content
  File "calibre_plugins.kobotouch_extended.container", line 381, in __run_async
  File "calibre_plugins.kobotouch_extended.container", line 377, in __run_async
  File "concurrent\futures\_base.py", line 449, in result
  File "concurrent\futures\_base.py", line 401, in __get_result
  File "concurrent\futures\thread.py", line 58, in run
  File "calibre_plugins.kobotouch_extended.container", line 523, in add_kobo_spans
  File "calibre_plugins.kobotouch_extended.container", line 589, in _add_kobo_spans_to_node
  File "calibre_plugins.kobotouch_extended.container", line 539, in _add_kobo_spans_to_node
  File "re\__init__.py", line 176, in search
TypeError: Failed to process BookName: expected string or bytes-like object, got '_cython_3_0_10.cython_function_or_method'

```
When modifying line 532 of container.py with:
`        if node is None or isinstance(node, (etree.CommentBase, etree.PIBase, etree._Comment)):
`
the node is bypassed, which is kind of strange, since etree._Comment should inherit from etree.CommentBase.

The problematic xhtml seems to be a simple comment in a body tag (file attached):
[nav.txt](https://github.com/user-attachments/files/16486790/nav.txt)

```
<!-- 
  <nav epub:type="page-list" id="page-list" hidden="">
    <ol>
      <li><a href="../Text/Filename001.xhtml#pagei"><b>i</b></a></li>
      <li><a href="../Text/Filename001.xhtml#page001"><b>1</b></a></li>
      <li><a href="../Text/Filename001.xhtml#page002"><b>2</b></a></li>
    </ol>
  </nav>
 -->

```

By removing these lines, the error disappeared.
(not attaching calibre log since there is too much private data at it, but i think the bug can easily be replicated using the steps below. Let me know if you need more info. thanks)

**Comment by jgoguen** [comment]
This one was just stupid. I'll upload the new versions to MobileRead shortly, calibre should offer the update within the hour after I get the new versions uploaded. You can also visit the Releases page for v3.6.10 when it shows up, grab the extensions from there, and install the new version manually.
