### ISSUE TITLE
Unable to send PDF to kobo device. "Not a ZIP file" error.

### ISSUE THREAD

**Issue by norbnorbnorb** [jgoguen/calibre-kobo-driver#173]
# Bug Checklist

These items are mandatory. If you need help finding this information submit the
bug report with as much completed as you can and ask for help finding the rest.

- [x] I am using the latest version of calibre to report this bug, which is: 7.16
- [x] I am using an official calibre release, not one from a third party (e.g.
    your Linux distro, Flatpak, Chocolatey package, Homebrew, etc.)
- [x] I am using the latest version of this plugin, which is: 3.6.10
- [x] My operating system is: Windows 11 pro
- [ ] I have included the full, complete, unmodified debug log from calibre 
  - I change the user name in the win file path and removed some items from the shelf list for privacy - all were standard latin characters [A-Za-z]
- [x] I have translated the text in any screenshots and logs to English, or all
    screenshots and logs included are in English.

These items are optional. Fill in as much of them as possible. If something is
not applicable to your bug report, note that.

- [ ] I have installed the Scramble Epub plugin (see
    https://www.mobileread.com/forums/showthread.php?t=267998) and will attach
    a **scrambled** copy of the book I'm having problems with (attach a file by
    dragging and dropping onto the Github editor).
  - [ ] If this is a conversion bug, I will also attach a **scrambled** copy of
    the converted book.
- [x] The path to my calibre library or to a book in my calibre library has
    non-ASCII characters: no
- [x] If I am using Windows 10, I have not enabled Windows' beta support
      for Unicode (see
      https://www.mobileread.com/forums/showpost.php?p=3988195&postcount=2052)
- [ ] If I am using Windows 10, does this bug happens with beta Unicode support
    both enabled and disabled, only when enabled, or only when disabled?

# Describe the bug
PDF fails to upload to kobo device. Error communication with device "Not a ZIP file".
In case it matters, same behavior if options -> extended -> send books as kepubs is off.

## Steps to Reproduce

1. Have kobo libra color connected.
2. Right click on a PDF file in library.
3. Use send to device -> send to main memory.
4. Error occurs and file is not sent to device.

## Expected behavior
PDF file is send to device as PDF without error.

## Actual behaviour
File transfer aborts due to error and PDF is not sent to device.

## Files
PDF file to reproduce:
[Quick Start Guide - John Schember.pdf](https://github.com/user-attachments/files/16512550/Quick.Start.Guide.-.John.Schember.pdf)

## Logs
debug log:

```
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 7.16  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Kobo Utilities (2, 17, 1) && KoboTouchExtended (3, 6, 10)
calibre 7.16  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Kobo Utilities (2, 17, 1) && KoboTouchExtended (3, 6, 10)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 108.73578595317724 x 108.85714285714285
[0.00] Starting up...
[0.00] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
DEBUG:    0.0 Kobo Utilities Configuration - CreateNewCustomColumn is supported
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 KoboUtilites::dialogs.py - loading translations
DEBUG:    0.0 KoboUtilites::action.py - loading translations
[0.58] GUI main window shown
DEBUG:    0.2 No Kobo Touch, Glo or Mini appears to be connected
DEBUG:    0.2 rebuild_menus - self.supports_ratings=None, self.supports_tiles=None
DEBUG:    0.2 KoboUtilities:set_toolbar_button_tooltip - start: text='None'
DEBUG:    0.2 KoboUtilities:set_toolbar_button_tooltip - setting to text='Utilities to use with Kobo ereaders

Driver: KoboTouchExtended'
[0.64] main UI initialized...
[0.64] Hiding splash screen
Storage number map:
{(7, 0): [(2, 'D')],
 (7, 1): [(3, 'C')],
 (7, 2): [(1, 'E')],
 (8, 0): [(4294967295, 'G')]}
Storage number for USBSTOR\DISK&VEN_LINUX&PROD_FILE-STOR_GADGET&REV_0409\N428450127714&0: StorageDeviceNumber(type=7, number=2, partition_number=0)
Drive letters for USBDevice(vendor_id=0x2237 product_id=0x4237 bcd=0x409 devid=usb\vid_2237&pid_4237&rev_0409 devinst=9)
{'drive_letters': ['E'],
 'pnp_id_map': {'E': '\\\\?\\usbstor#disk&ven_linux&prod_file-stor_gadget&rev_0409#n428450127714&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 'readonly_drives': set(),
 'sort_map': {'E': (2, 1)}}
DEBUG:    5.2 KoboUtilities:_on_device_connection_changed - self.plugin_device_connection_changed.__class__:  <class 'PyQt6.QtCore.pyqtBoundSignal'>
DEBUG:    5.2 Methods for self.plugin_device_connection_changed:  ['__call__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'connect', 'disconnect', 'emit', 'signal']
DEBUG:    5.2 Have a Kobo device connected connected
DEBUG:    5.2 BEGIN Get Device Path
DEBUG:    5.2 Root path of device: E:\
DEBUG:    5.2 END Get Device Path
DEBUG:    5.2 KoboUtilities:get_device - self.device_path="E:\"
DEBUG:    5.2 KoboUtilities:set_toolbar_button_tooltip - start: text='None'
DEBUG:    5.2 KoboUtilities:set_toolbar_button_tooltip - setting to text='Utilities to use with Kobo ereaders

Driver: KoboTouchExtended'
Job: 0 Get device information started
DEBUG:    0.0 device_version_info - start
DEBUG:    0.0 device_version_info - version_file=E:\.kobo\version
DEBUG:    0.0 device_version_info - have opened version_file
DEBUG:    0.0 device_version_info - self._device_version_info= ['N428450127714', '4.9.77', '4.39.23027', '4.9.77', '4.9.77', '00000000-0000-0000-0000-000000000390']
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 KoboTouch:books - oncard='None'
2024-08-06 17:05:00 [DEBUG] KoboTouchExtended:settings: settings=                                                                  2024-08-06 17:05:00 [DEBUG] <calibre.utils.config_base.OptionValues object at 0x000002CDE59F1590>
DEBUG:    0.0 KoboTouch:books - oncard='None', prefix='E:\'
DEBUG:    0.0 device_version_info - start
DEBUG:    0.0 Kobo device: Kobo Libra Colour
DEBUG:    0.0 Version of driver: (3, 6, 10) Has kepubs: True
DEBUG:    0.0 Version of firmware: (4, 39, 23027) Has kepubs: True
DEBUG:    0.0 Firmware supports cover image tree: True
2024-08-06 17:05:00 [DEBUG] KoboTouchExtended:settings: settings=                                                                  2024-08-06 17:05:00 [DEBUG] <calibre.utils.config_base.OptionValues object at 0x000002CDE59F0790>
DEBUG:    0.0 KoboTouch:books - opts.extra_customization= []
DEBUG:    0.0 KoboTouch:books - driver options= Driver:KoboTouchExtended, Options - format_map: ['kepub', 'epub', 'cbr', 'cbz', 'pdf', 'txt'], use_subdirs: True, read_metadata: True, use_author_sort: False, save_template: /{#collection}/{series}/{title} - {authors} - {author_sort}, extra_customization: [], manage_collections: True, use_collections_columns: True, collections_columns: #collection, use_collections_template: False, collections_template: , create_collections: True, delete_empty_collections: False, ignore_collections_names: , upload_covers: False, dithered_covers: False, keep_cover_aspect: False, upload_grayscale: False, letterbox_fs_covers: False, letterbox_fs_covers_color: #000000, png_covers: False, show_archived_books: False, show_previews: False, show_recommendations: False, update_series: True, force_series_id: False, update_core_metadata: True, update_purchased_kepubs: False, update_device_metadata: True, update_subtitle: False, subtitle_template: , update_bookstats: False, bookstats_wordcount_template: , bookstats_pagecount_template: , bookstats_timetoread_upper_template: , bookstats_timetoread_lower_template: , modify_css: False, override_kobo_replace_existing: True, support_newer_firmware: False, debugging_title: , driver_version: 3.6.7, extra_features: True, use_template: False, kepubify_template: , upload_encumbered: False, skip_failed: False, hyphenate: False, smarten_punctuation: False, clean_markup: False, full_page_numbers: False, disable_hyphenation: False, file_copy_dir: , hyphenate_chars: 6, hyphenate_chars_before: 3, hyphenate_chars_after: 3, hyphenate_limit_lines: 2
DEBUG:    0.0 KoboTouch:books - prefs['manage_device_metadata']= manual
DEBUG:    0.0 KoboTouch:books - set_debugging_title to ''
DEBUG:    0.0 KoboTouch:books - length bl=0
DEBUG:    0.1 KoboTouch:books - length bl after sync=215
DEBUG:    0.1 KoboTouch:books - reading device database
DEBUG:    0.1 Database Version:  175
DEBUG:    0.1 KoboTouch:books - shelf list: ['Novels', 'Allgemeine Psychologie', 'Comics & Graphic Novels', 'Anatomie', 'Papers']
DEBUG:    0.1 KoboTouch:books - query= SELECT Title, Attribution, DateCreated, ContentID, MimeType, ContentType, ImageId, ReadStatus, Description, Publisher , ___ExpirationStatus, FavouritesIndex, Accessibility, Language, IsDownloaded, ISBN, Series, SeriesNumber, ___UserID, ExternalId, Subtitle, SeriesID, SeriesNumberFloat, StorePages, StoreWordCount, StoreTimeToReadLowerEstimate, StoreTimeToReadUpperEstimate FROM content  WHERE BookID IS NULL  AND ((Accessibility = -1 AND IsDownloaded in ('true', 1 ))       OR (Accessibility IN (1,2,8,9) and IsDownloaded in ('true', 1))         )  AND (externalId IS NULL OR externalId = '') AND contentId NOT LIKE 'file:///mnt/sd/%'
DEBUG:    0.2 KoboTouch:books - self.kobo_series_dict= {}
DEBUG:    0.2 KoboTouch:books - about to sync_booklists
DEBUG:    0.2 USBMS: starting sync_booklists
DEBUG:    0.3 USBMS: finished sync_booklists
DEBUG:    0.3 KoboTouch:books - have done sync_booklists
DEBUG:    0.3 KoboTouch:books - end - oncard='None'
DEBUG:    0.3 KoboTouch:books - oncard='carda'
DEBUG:    0.3 KoboTouch:books - Asked to process 'carda', but do not have one!
DEBUG:    0.3 KoboTouch:books - oncard='cardb'
DEBUG:    0.3 KoboTouch:books - Asked to process 'cardb', but do not have one!
DeviceJob: 2 Get list of books on device done, calling callback
DEBUG:    0.3 DeviceJob: metadata_downloaded: Starting set_books_in_library
DEBUG:    0.3 DeviceJob: set_books_in_library: books to process= 215
DEBUG:    0.4 DeviceJob: set_books_in_library finished: time= 0.006000518798828125
DEBUG:    0.4 DeviceJob: metadata_downloaded: updating views
DEBUG:    0.4 DeviceJob: metadata_downloaded: syncing
2024-08-06 17:05:00 [DEBUG] KoboTouchExtended:settings: settings=                                                                  2024-08-06 17:05:00 [DEBUG] <calibre.utils.config_base.OptionValues object at 0x000002CDE7EC8950>
2024-08-06 17:05:00 [DEBUG] KoboTouchExtended:settings: settings=                                                                  2024-08-06 17:05:00 [DEBUG] <calibre.utils.config_base.OptionValues object at 0x000002CDE5BBC210>
DEBUG:    0.4 DeviceJob: metadata_downloaded: refreshing ondevice
DEBUG:    0.4 DeviceJob: metadata_downloaded: sending metadata_available signal
DEBUG:    5.5 KoboUtilites:_on_device_metadata_available - Start
DEBUG:    5.5 Have a Kobo device connected connected
DEBUG:    5.5 BEGIN Get Device Path
DEBUG:    5.5 Root path of device: E:\
DEBUG:    5.5 END Get Device Path
DEBUG:    5.5 KoboUtilities:get_device - self.device_path="E:\"
DEBUG:    5.5 KoboUtilities:get_device - drive_info: {'main': {'device_store_uuid': 'ded56bf8-3257-4143-8ee9-1c14dae61c26', 'device_name': 'Kobo Libra Colour', 'location_code': 'main', 'last_library_uuid': None, 'calibre_version': '7.16.0', 'date_last_connected': '2024-08-06T15:05:00.286564+00:00', 'prefix': 'E:/'}}
DEBUG:    5.5 migrate_library_config_if_required - start
DEBUG:    5.5 get_library_config - library_config: {'profiles': {'Default': {'forDevice': None, 'storeOptionsStore': {'storeOnConnect': False, 'promptToStore': True, 'storeIfMoreRecent': False, 'doNotStoreIfReopened': False}}}, 'SchemaVersion': 0.1}
DEBUG:    5.5 KoboUtilities:get_device - device_name: Kobo Libra Colour
DEBUG:    5.5 get_plugin_pref - start - store_name='commonOptionsStore', option='individualDeviceOptions'
DEBUG:    5.5 get_prefs - start - store_name='backupOptionsStore'
DEBUG:    5.5 KoboUtilities:set_toolbar_button_tooltip - start: text='None'
DEBUG:    5.5 KoboUtilities:set_toolbar_button_tooltip - device connected. self.device.fwversion= (4, 39, 23027)
DEBUG:    5.5 KoboUtilities:set_toolbar_button_tooltip - setting to text='Utilities to use with Kobo ereaders

Connected Device: Kobo Libra Colour
Firmware version: 4.39.23027
Driver: KoboTouchExtended'
DEBUG:    5.5 KoboUtilites:_on_device_metadata_available - self.current_device_profile: None
DEBUG:    5.5 KoboUtilites:_on_device_metadata_available - self.current_backup_config: {'doDailyBackp': False, 'backupEachCOnnection': False, 'backupCopiesToKeepSpin': 5, 'backupDestDirectory': '', 'backupZipDatabase': True}
DEBUG:    5.5 Have a Kobo device connected connected
DEBUG:    5.5 BEGIN Get Device Path
DEBUG:    5.5 Root path of device: E:\
DEBUG:    5.5 END Get Device Path
DEBUG:    5.5 KoboUtilities:get_device - self.device_path="E:\"
DEBUG:    5.5 KoboUtilities:get_device - drive_info: {'main': {'device_store_uuid': 'ded56bf8-3257-4143-8ee9-1c14dae61c26', 'device_name': 'Kobo Libra Colour', 'location_code': 'main', 'last_library_uuid': None, 'calibre_version': '7.16.0', 'date_last_connected': '2024-08-06T15:05:00.286564+00:00', 'prefix': 'E:/'}}
DEBUG:    5.5 migrate_library_config_if_required - start
DEBUG:    5.5 get_library_config - library_config: {'profiles': {'Default': {'forDevice': None, 'storeOptionsStore': {'storeOnConnect': False, 'promptToStore': True, 'storeIfMoreRecent': False, 'doNotStoreIfReopened': False}}}, 'SchemaVersion': 0.1}
DEBUG:    5.5 KoboUtilities:get_device - device_name: Kobo Libra Colour
DEBUG:    5.5 get_plugin_pref - start - store_name='commonOptionsStore', option='individualDeviceOptions'
DEBUG:    5.5 get_prefs - start - store_name='backupOptionsStore'
DEBUG:    5.5 rebuild_menus - self.supports_ratings=True, self.supports_tiles=True
DEBUG:    5.5 KoboUtilities:set_toolbar_button_tooltip - start: text='None'
DEBUG:    5.5 KoboUtilities:set_toolbar_button_tooltip - device connected. self.device.fwversion= (4, 39, 23027)
DEBUG:    5.5 KoboUtilities:set_toolbar_button_tooltip - setting to text='Utilities to use with Kobo ereaders

Connected Device: Kobo Libra Colour
Firmware version: 4.39.23027
Driver: KoboTouchExtended'
DEBUG:    5.5 rebuild_menus - have device.
DeviceJob: 2 Get list of books on device callback returned
Job: 0 Get device information finished
No details available.
Job: 2 Get list of books on device finished
No details available.
Job: 1 Set library information finished
No details available.
[20.42] splash screen hidden
[20.42] Started up in 20.42 seconds with 1 books
2024-08-06 17:05:22 [DEBUG] KoboTouchExtended:settings: settings=                                                                  2024-08-06 17:05:22 [DEBUG] <calibre.utils.config_base.OptionValues object at 0x000002CDE5BBDF90>
Job: 3 Upload one book to the device: Quick Start Guide started
Device using plugboard pdf KOBOTOUCHEXTENDED None
Setting metadata in: Quick Start Guide at: C:\Users\user01\AppData\Local\Temp\calibre_u5s2y5ak\9n3s1mz5caltmpfmt.pdf
DEBUG:   22.6 KoboTouch:upload_books - 1 books
DEBUG:   22.6 KoboTouch:upload_books - files= ['C:\\Users\\user01\\AppData\\Local\\Temp\\calibre_u5s2y5ak\\9n3s1mz5caltmpfmt.pdf']
DEBUG:   22.6 KoboTouch:upload_books: Processing book: Quick Start Guide by John Schember
DEBUG:   22.6 KoboTouch:upload_books: file=C:\Users\user01\AppData\Local\Temp\calibre_u5s2y5ak\9n3s1mz5caltmpfmt.pdf, name=Quick Start Guide - John Schember_1.pdf
2024-08-06 17:05:22 [ERROR] EPUB appears to be invalid ZIP file, trying a more forgiving ZIP parser
Traceback (most recent call last):
  File "calibre\ebooks\oeb\polish\container.py", line 1181, in __init__
  File "calibre\utils\zipfile.py", line 774, in __init__
  File "calibre\utils\zipfile.py", line 809, in _GetContents
  File "calibre\utils\zipfile.py", line 824, in _RealGetContents
calibre.utils.zipfile.BadZipfile: File is not a zip file

Not a ZIP file

Traceback (most recent call last):
  File "calibre\ebooks\oeb\polish\container.py", line 1181, in __init__
  File "calibre\utils\zipfile.py", line 774, in __init__
  File "calibre\utils\zipfile.py", line 809, in _GetContents
  File "calibre\utils\zipfile.py", line 824, in _RealGetContents
calibre.utils.zipfile.BadZipfile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\gui2\device.py", line 112, in run
  File "calibre\gui2\device.py", line 646, in _upload_books
  File "calibre_plugins.kobotouch_extended.device.driver", line 342, in upload_books
  File "calibre\devices\kobo\driver.py", line 2270, in upload_books
  File "calibre_plugins.kobotouch_extended.device.driver", line 152, in _modify_epub
  File "calibre_plugins.kobotouch_extended.container", line 117, in __init__
  File "calibre\ebooks\oeb\polish\container.py", line 1188, in __init__
  File "calibre\utils\localunzip.py", line 255, in extractall
  File "calibre\utils\localunzip.py", line 242, in _extractall
ValueError: Not a ZIP file

```

## Additional context
Same result using driver v3.6.9.
For v3.6.10 I tested to upload PDF on 2 different PCs, using the same settings on calibre and I tested with a new library without custom columns or other modifications.
Same behavior on all theses tests.

Using driver v3.6.7 works as expected and sends the PDF to the device without issue on both PCs.

**Comment by jgoguen** [comment]
v3.6.11 fixes PDF uploads. Calibre should offer it within the next hour, or you can grab the ZIP file from the v3.6.11 release page and install it manually.
