### ISSUE TITLE
'NoneType' object has no attribute '__getitem__' (3.1.5)

### ISSUE THREAD

**Issue by relusionary** [jgoguen/calibre-kobo-driver#79]
All fine until updating to Calibre 4.3.0. Then communication with device wasn't possible.
Attempted uninstall/reinstall and multiple restarts. 

Using KoboTouchExtended 3.1.5

///

calibre, version 4.3.0
ERROR: Error: Error communicating with device

'NoneType' object has no attribute '__getitem__'

Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 90, in run
  File "site-packages\calibre\gui2\device.py", line 594, in _upload_books
  File "calibre_plugins.kobotouch_extended.device.driver", line 399, in upload_books
  File "site-packages\calibre\devices\kobo\driver.py", line 2095, in upload_books
  File "calibre_plugins.kobotouch_extended.device.driver", line 313, in _modify_epub
  File "site-packages\calibre\startup.py", line 89, in expanduser
TypeError: 'NoneType' object has no attribute '__getitem__'

[tmpbrrg1q-kobo-debug-file.txt](https://github.com/jgoguen/calibre-kobo-driver/files/3850995/tmpbrrg1q-kobo-debug-file.txt)

**Comment by relusionary** [comment]
👌 replaced plugin and books are once again transferring. Amazing - thanks!
