### ISSUE TITLE
KePub Conversion Error

### ISSUE THREAD

**Issue by Tamarissa** [jgoguen/calibre-kobo-driver#80]
I receive this error when I try to open a newly created kepub:

calibre, version 4.5.0
ERROR: Loading book failed: Failed to open the book at /Users/Mona/Library/Mobile Documents/com~apple~CloudDocs/Books/Rachel Vincent/Wild Card (2464)/Wild Card - Rachel Vincent.kepub. Click "Show details" for more info.

Traceback (most recent call last):
  File "site-packages/calibre/gui2/viewer/ui.py", line 360, in _load_ebook_worker
  File "site-packages/calibre/gui2/viewer/convert_book.py", line 231, in prepare_book
  File "site-packages/calibre/gui2/viewer/convert_book.py", line 188, in do_convert
ConversionFailure: Failed to convert book: /Users/Mona/Library/Mobile Documents/com~apple~CloudDocs/Books/Rachel Vincent/Wild Card (2464)/Wild Card - Rachel Vincent.kepub with error:
Python function terminated unexpectedly: No plugin to handle input format: kepub
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 163, in main
    return run_entry_point()
  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 121, in run_entry_point
    return getattr(pmod, func)()
  File "site-packages/calibre/utils/ipc/worker.py", line 189, in main
  File "<string>", line 1, in <module>
  File "site-packages/calibre/srv/render_book.py", line 830, in viewer_main
  File "site-packages/calibre/srv/render_book.py", line 823, in render_for_viewer
  File "site-packages/calibre/srv/render_book.py", line 798, in render
  File "site-packages/calibre/ebooks/oeb/iterator/book.py", line 54, in extract_book
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 755, in __init__
ValueError: No plugin to handle input format: kepub

**What version of calibre are you running?** 4.5
**What version of the plugin are you using?** 3.1.3 - no idea if this is the latest version... I downloaded the zip file, but there's nothing in it for Calibre to work with. Also tried individual files, but none were compatible. Doesn't appear to be any, as using the Calibre update plugin feature doesn't show anything needing updating.
<img width="443" alt="Screen Shot 2019-12-02 at 8 20 46 AM" src="https://user-images.githubusercontent.com/58387230/69971160-b62d3c80-14dc-11ea-8edf-e5baf62a8085.png">
calibre, version 4.5.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'/Users/Mona/Downloads/KePub Output.zip' is invalid. It does not contain a top-level __init__.py file
calibre 4.5  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3) && EpubMerge (2, 5, 0) && Kobo Utilities (2, 9, 0) && Fantastic Fiction (1, 3, 0) && Kobo Books (1, 7, 0) && Fantastic Fiction Adults (1, 1, 0) && Reading List (1, 6, 6) && Goodreads (1, 4, 0) && KePub Output (3, 1, 3) && Obok DeDRM (6, 5, 4) && KePub Metadata Reader (3, 0, 2) && EpubSplit (2, 7, 0) && Count Pages (1, 9, 0) && KePub Metadata Writer (3, 0, 3) && Barnes & Noble (1, 2, 15)
Traceback (most recent call last):
  File "site-packages/calibre/gui2/preferences/plugins.py", line 319, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 472, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 61, in load_plugin
  File "site-packages/calibre/customize/zipplugin.py", line 194, in load
  File "site-packages/calibre/customize/zipplugin.py", line 292, in _locate_code
InvalidPlugin: The plugin in u'/Users/Mona/Downloads/KePub Output.zip' is invalid. It does not contain a top-level __init__.py file
**Are you able to send me a book that demonstrates the problem?** Would love too... no instructions on where to send it provided that I could see.
**The calibre debug log showing the issue, where possible**
[tmp3eqHqO.txt](https://github.com/jgoguen/calibre-kobo-driver/files/3911959/tmp3eqHqO.txt)

**Comment by Technicalleigh** [comment]
>  Python function terminated unexpectedly: No plugin to handle input format: kepub

Did you install the KePub Input plugin also? I believe Calibre's built-in reader converts the book into HTML before displaying it.
