### ISSUE TITLE
Error during install on Ubuntu 20.04: KePub Metadata Writer and Kobo Touch Extended

### ISSUE THREAD

**Issue by 0scubasteve0** [jgoguen/calibre-kobo-driver#83]
I am not able to install the following plugins on either of my Kubuntu 20.04 machines:

Kepub Metadata Writer
Kobo Touch Extended

Below are the error tracebacks I receive for each:

**Kepub Metadata Writer:**
```
calibre, version 4.99.4
ERROR: Install plugin failed: A problem occurred while installing this plugin. This plugin will now be uninstalled. Please post the error message in details below into the forum thread for this plugin and restart calibre.

Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/dialogs/plugin_updater.py", line 725, in _install_clicked
    plugin = add_plugin(zip_path)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 472, in add_plugin
    plugin = load_plugin(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 61, in load_plugin
    return loader.load(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 202, in load
    m = importlib.import_module(plugin_module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 184, in load_module
    exec(compiled, mod.__dict__)
  File "calibre_plugins.kepubmdwriter.__init__", line 7, in <module>
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 184, in load_module
    exec(compiled, mod.__dict__)
  File "calibre_plugins.kepubmdwriter.metadata.writer", line 9, in <module>
ModuleNotFoundError: No module named 'cStringIO'
```

**KoboTouchExtended:**

```
calibre, version 4.99.4

ERROR: Install plugin failed: A problem occurred while installing this plugin. This plugin will now be uninstalled. Please post the error message in details below into the forum thread for this plugin and restart calibre.

Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/dialogs/plugin_updater.py", line 725, in _install_clicked
    plugin = add_plugin(zip_path)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 472, in add_plugin
    plugin = load_plugin(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 61, in load_plugin
    return loader.load(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 202, in load
    m = importlib.import_module(plugin_module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 184, in load_module
    exec(compiled, mod.__dict__)
  File "calibre_plugins.kobotouch_extended.__init__", line 9, in <module>
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 184, in load_module
    exec(compiled, mod.__dict__)
  File "calibre_plugins.kobotouch_extended.device.driver", line 14, in <module>
ModuleNotFoundError: No module named 'ConfigParser'
```

Could this be related to the removal of Python2 from Ubuntu 20.04? Any guidance here would be appreciated.

Thank you!

**Comment by norbusan** [comment]
Yes, Calibre in Debian and thus also in Ubuntu is now based on Python3, since Python2 is in the process of being purged.

Most plugins, including these ones, are not already updated to Python3, and thus fail to work.

**Comment by 0scubasteve0** [comment]
As I suspected. I installed the latest plugin zips from Keybase and was able to install them but I get errors during conversion.

**Comment by norbusan** [comment]
What you can do is clone the git repo, checkout the py3k branch, build your own zip from there and install it - and then report, or better fix what is not working :-)

**Comment by 0scubasteve0** [comment]
Great, I will try that, thank you. Sadly I'm not a developer so I can only report bugs :(. Appreciate all your work on this.

**Comment by jgoguen** [comment]
This is the removal of Python 2. If you install calibre using one of the supported methods you won't run into this issue. I do have a Python 3-compatible plugin version to release soon (not the version in Keybase, that's a testing version and isn't the latest code) but only installing calibre from the official upstream package is supported.

**Comment by 0scubasteve0** [comment]
@jgoguen By supported methods do you mean installing from Calibre directly? That's what I tried on first attempt which caused the error. Glad to hear there is a new release soon!

**Comment by 0scubasteve0** [comment]
Also is there a create-plugin.sh script I can use to build from source? I only see the PowerShell version available.

**Comment by norbusan** [comment]
No, he means installing the Linux package provided by Calibre upstream, and not the Ubuntu package. That is do **not** use `apt install calibre`. But I disagree here, Debian/Ubuntu package is 99% the same as upstream, only that it switched to Py3.

**Comment by 0scubasteve0** [comment]
Ah that fixed it! Didn't even realize the Calibre team recommended a binary install. Thank you for the help.

**Comment by jgoguen** [comment]
It's a matter of support, not similarity. Calibre isn't yet supported on Python 3 (but it runs, Kovid seems to be close to finishing the Python 3 port), the Debian package uses Python 3, the Debian package is running in an explicitly unsupported state. Kovid has said many times that any install package other than the one provided on the calibre site is not supported and "at your own risk". But hopefully soon I'll finish the last little bit of the Python 3 port of these and get a new version released, but installing outside the official calibre upstream packages is still unsupported (any issues need to be reproduced with the current upstream build).

**Comment by jgoguen** [comment]
New versions of the plugins were recently published to MobileRead, IIRC Kovid's scripts poll for new plugins there every hour so calibre should make them available soon. You're looking for version 3.2.2.
