### ISSUE TITLE
cannot convert traditional chinese ebook from epub to kepub

### ISSUE THREAD

**Issue by blindman102** [jgoguen/calibre-kobo-driver#87]
old version is OK but fail to convert after update recently

Here is the error code:

calibre, version 4.15.0 (win32, embedded-python: True)
Conversion error: Failed: Convert book 1 of 1 (理想的小白臉生活13)

Convert book 1 of 1 (理想的小白臉生活13)
C:\Program Files (x86)\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Conversion options changed from defaults:
  verbose: 2
  enable_heuristics: True
  cover: u'C:\\Users\\kunwm\\AppData\\Local\\Temp\\calibre_n2riv_\\iex4yg.jpeg'
  read_metadata_from_opf: u'C:\\Users\\kunwm\\AppData\\Local\\Temp\\calibre_n2riv_\\fqsonr.opf'
  output_profile: u'kindle_pw3'
  preserve_cover_aspect_ratio: True
Resolved conversion options
calibre version: 4.15.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'C:\\Users\\kunwm\\AppData\\Local\\Temp\\calibre_n2riv_\\iex4yg.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_split_on_page_breaks': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': True,
 'epub_flatten': False,
 'epub_inline_toc': False,
 'epub_toc_at_end': False,
 'epub_version': u'2',
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': u'',
 'fix_indents': True,
 'flow_size': 260,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0567BFB0>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'kepub_clean_markup': True,
 'kepub_disable_hyphenation': False,
 'kepub_hyphenate': True,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_default_epub_cover': False,
 'no_inline_navbars': False,
 'no_svg_cover': False,
 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x056823D0>,
 'page_breaks_before': u'/',
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': True,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\kunwm\\AppData\\Local\\Temp\\calibre_n2riv_\\fqsonr.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: EPUB Input running
on C:\Users\kunwm\AppData\Local\Temp\calibre_n2riv_\oizcwo.epub
Found HTML cover OEBPS/Text/cover.xhtml
Parsing all content...
Parsing OEBPS/Text/Section0009.xhtml ...
*********  Heuristic processing HTML  *********
There are 0 blank lines. 0.0 percent blank
minimum chapters required are: 3
found 1 pre-existing headings
Total wordcount is: 17897, Average words per section is: 17897, Marked up 1 chapters
Hard line breaks check returned True
Median line length is 49, calculated with html format
Unwrapping required, unwrapping Lines
Fixing hyphenated content
Looking for more split points based on punctuation, currently have 1
Formatting scene breaks
Parsing OEBPS/Text/Section0003.xhtml ...
*********  Heuristic processing HTML  *********
There are 0 blank lines. 0.0 percent blank
minimum chapters required are: 1
found 1 pre-existing headings
Total wordcount is: 3253, Average words per section is: 3253, Marked up 1 chapters
Hard line breaks check returned True
Median line length is 30, calculated with html format
Unwrapping required, unwrapping Lines
Fixing hyphenated content
Formatting scene breaks
Parsing OEBPS/Text/Section0004.xhtml ...
*********  Heuristic processing HTML  *********
There are 0 blank lines. 0.0 percent blank
minimum chapters required are: 4
found 1 pre-existing headings
Total wordcount is: 22773, Average words per section is: 22773, Marked up 1 chapters
Hard line breaks check returned True
Median line length is 53, calculated with html format
Unwrapping required, unwrapping Lines
Fixing hyphenated content
Looking for more split points based on punctuation, currently have 1
Formatting scene breaks
Parsing OEBPS/Text/Section0005.xhtml ...
*********  Heuristic processing HTML  *********
There are 0 blank lines. 0.0 percent blank
minimum chapters required are: 3
found 1 pre-existing headings
Total wordcount is: 15232, Average words per section is: 15232, Marked up 1 chapters
Hard line breaks check returned True
Median line length is 44, calculated with html format
Unwrapping required, unwrapping Lines
Fixing hyphenated content
Looking for more split points based on punctuation, currently have 1
Formatting scene breaks
Parsing OEBPS/Text/cover.xhtml ...
*********  Heuristic processing HTML  *********
flow is too short, not running heuristics
Parsing OEBPS/Text/Section0002.xhtml ...
*********  Heuristic processing HTML  *********
flow is too short, not running heuristics
Parsing OEBPS/Text/Section0011.xhtml ...
*********  Heuristic processing HTML  *********
There are 0 blank lines. 0.0 percent blank
minimum chapters required are: 2
found 1 pre-existing headings
Total wordcount is: 7678, Average words per section is: 7678, Marked up 1 chapters
Hard line breaks check returned True
Median line length is 35, calculated with html format
Unwrapping required, unwrapping Lines
Fixing hyphenated content
Looking for more split points based on punctuation, currently have 1
Formatting scene breaks
Parsing OEBPS/Text/Section0006.xhtml ...
*********  Heuristic processing HTML  *********
There are 0 blank lines. 0.0 percent blank
minimum chapters required are: 2
found 1 pre-existing headings
Total wordcount is: 9229, Average words per section is: 9229, Marked up 1 chapters
Hard line breaks check returned True
Median line length is 44, calculated with html format
Unwrapping required, unwrapping Lines
Fixing hyphenated content
Looking for more split points based on punctuation, currently have 1
Formatting scene breaks
Parsing OEBPS/Text/Section0010.xhtml ...
*********  Heuristic processing HTML  *********
There are 0 blank lines. 0.0 percent blank
minimum chapters required are: 3
found 1 pre-existing headings
Total wordcount is: 19796, Average words per section is: 19796, Marked up 1 chapters
Hard line breaks check returned True
Median line length is 43, calculated with html format
Unwrapping required, unwrapping Lines
Fixing hyphenated content
Looking for more split points based on punctuation, currently have 1
Formatting scene breaks
Parsing OEBPS/Text/Section0008.xhtml ...
*********  Heuristic processing HTML  *********
There are 0 blank lines. 0.0 percent blank
minimum chapters required are: 1
found 1 pre-existing headings
Total wordcount is: 6597, Average words per section is: 6597, Marked up 1 chapters
Hard line breaks check returned True
Median line length is 35, calculated with html format
Unwrapping required, unwrapping Lines
Fixing hyphenated content
Formatting scene breaks
Parsing OEBPS/Text/Section0001.xhtml ...
*********  Heuristic processing HTML  *********
There are 0 blank lines. 0.0 percent blank
minimum chapters required are: 1
found 1 pre-existing headings
Total wordcount is: 205, Average words per section is: 205, Marked up 1 chapters
Hard line breaks check returned True
Median line length is 198, calculated with html format
Unwrapping required, unwrapping Lines
Fixing hyphenated content
Formatting scene breaks
Parsing OEBPS/Text/Section0012.xhtml ...
*********  Heuristic processing HTML  *********
There are 0 blank lines. 0.0 percent blank
minimum chapters required are: 2
found 1 pre-existing headings
Total wordcount is: 13062, Average words per section is: 13062, Marked up 1 chapters
Hard line breaks check returned True
Median line length is 39, calculated with html format
Unwrapping required, unwrapping Lines
Fixing hyphenated content
Looking for more split points based on punctuation, currently have 1
Formatting scene breaks
Parsing OEBPS/Text/Section0013.xhtml ...
*********  Heuristic processing HTML  *********
There are 0 blank lines. 0.0 percent blank
minimum chapters required are: 1
found 1 pre-existing headings
Total wordcount is: 105, Average words per section is: 105, Marked up 1 chapters
Hard line breaks check returned False
Median line length is 10, calculated with html format
Fixing hyphenated content
Formatting scene breaks
Parsing OEBPS/Text/Section0007.xhtml ...
*********  Heuristic processing HTML  *********
There are 0 blank lines. 0.0 percent blank
minimum chapters required are: 3
found 1 pre-existing headings
Total wordcount is: 16939, Average words per section is: 16939, Marked up 1 chapters
Hard line breaks check returned True
Median line length is 48, calculated with html format
Unwrapping required, unwrapping Lines
Fixing hyphenated content
Looking for more split points based on punctuation, currently have 1
Formatting scene breaks
Reading TOC from NCX...
Merging user specified metadata...
Detecting structure...
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Found 2603 items of level: p_1
p_1  left margin stats: Counter({u'0': 2603})
p_1  right margin stats: Counter({u'0': 2603})
Cleaning up manifest...
Trimming unused files from manifest...
Trimming u'OEBPS/Text/cover.xhtml' from manifest
Creating KePub Output...
Python function terminated unexpectedly
  'utf8' codec can't decode byte 0xa4 in position 20: invalid start byte (Error Code: 1)
 Traceback (most recent call last):
  File "site.py", line 114, in main
  File "site.py", line 88, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1275, in run
  File "calibre_plugins.kepubout.conversion.kepub_output", line 106, in convert
  File "calibre_plugins.kepubout.common", line 95, in print_formatted_log
  File "calibre_plugins.kepubout.common", line 84, in _tag_args
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa4 in position 20: invalid start byte

**Comment by blindman102** [comment]
also occur in kobo touch extended driver while syn with kobo

calibre, version 4.15.0
ERROR: Error: Error communicating with device

'utf8' codec can't decode byte 0xa4 in position 20: invalid start byte

Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 90, in run
  File "site-packages\calibre\gui2\device.py", line 513, in _books
  File "site-packages\calibre\devices\kobo\driver.py", line 1565, in books
  File "site-packages\calibre\devices\kobo\driver.py", line 3542, in get_debugging_title
  File "site-packages\calibre\devices\kobo\driver.py", line 3264, in get_pref
  File "calibre_plugins.kobotouch_extended.device.driver", line 113, in settings
  File "calibre_plugins.kobotouch_extended.common", line 95, in print_formatted_log
  File "calibre_plugins.kobotouch_extended.common", line 84, in _tag_args
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa4 in position 20: invalid start byte
